#ifndef INC_DEV_TYPE_TSC1_H_
#define INC_DEV_TYPE_TSC1_H_
#include "main.h"
#include "MEMORY_TSC1.h"
#include "NEWIO/newdevice.h"
#include <stdint.h>
typedef enum
{
    nothing,
    unix_time,
    obc_imu1,
    obc_imu2,
    obc_mag1,
    obc_mag2,
    obc_temp1,
    obc_current,
    model_igrf,
    model_sun,
    model_posvel_ecef,
    sat_inertia,
    obc_mtq1,
    obc_mtq2,
    obc_mtq3,
    obc_rwa1,
    obc_rwa2,
    obc_rwa3,
    obc_rwa4,
    cube_acs,
    cube_ads,
    cube_sun,
    cube_mag,
    cube_gyro,
    cube_nadir,
    cube_posvel_ecef,
    cube_est_rate,
    cube_est_quat,
    cube_mtq1,
    cube_mtq2,
    cube_mtq3,
    cube_rwa1,
    cube_rwa2,
    cube_rwa3,
    mem,
    rwa,
    mtq,
    can,
    uart,
    i2c,
    slave,
    acs,
    ads,
    run,
} device_no_t;

enum class DEV_TYPE_TSC1: uint8_t
{
	nothing = 0,
	clock = 1,
	gyro = 2,
	magnet = 3,
	temp = 4,
	current = 5,
	sunsen = 6,
	gps = 7,
	inertia = 8,
	obc_mtq = 9,
	obc_rwa = 10,
	obc_mode = 11,
	nadir = 12,
	star = 13,
	cube_mtq = 14,
	cube_rwa = 15,
};
// Declare class array to store device states
#define DEVICE_NMAX_DEV_TYPE_TSC1 45
NEW_DEVICE_STATE<DEV_TYPE_TSC1> mydevice[DEVICE_NMAX_DEV_TYPE_TSC1];

// Function to initialize device parameters
void init_device()
{
    // Initialize devices with corresponding command and sense pointers
	mydevice[(int)device_no_t::nothing].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::nothing,
		nullptr,
		(uint8_t*)&ram_data.sen_nothing,
		0.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::unix_time].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::clock,
		nullptr,
		(uint8_t*)&rom_data.sen_unix_time,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_imu1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_imu1[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_imu1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,90.0,180.0}}
	);
	mydevice[(int)device_no_t::obc_imu2].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_imu2[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_imu2}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{90.0,0.0,90.0}}
	);
	mydevice[(int)device_no_t::obc_mag1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_mag1[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_mag2].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_mag2[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_temp1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::temp,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_temp1,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_current].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::current,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_current,
		0.01,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::model_igrf].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_model_igrf[0],
		1.0,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::model_sun].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_model_sun[0],
		1.0,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::model_posvel_ecef].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::gps,
		nullptr,
		(uint8_t*)&ram_data.sen_model_posvel_ecef[0],
		1.0,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::sat_inertia].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::inertia,
		nullptr,
		(uint8_t*)&rom_data.sen_sat_inertia[0],
		1.0,
		0,
		6,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_mtq1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mtq,
		(uint8_t*)&ram_data.cmd_obc_mtq1,
		(uint8_t*)&ram_data.sen_obc_mtq1,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_obc_mtq1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::obc_mtq2].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mtq,
		(uint8_t*)&ram_data.cmd_obc_mtq2,
		(uint8_t*)&ram_data.sen_obc_mtq2,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_obc_mtq2}
		,angle_array_t<1>{{sat_dir_enum_t::yPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::yPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::obc_mtq3].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mtq,
		(uint8_t*)&ram_data.cmd_obc_mtq3,
		(uint8_t*)&ram_data.sen_obc_mtq3,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_obc_mtq3}
		,angle_array_t<1>{{sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::obc_rwa1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_rwa,
		(uint8_t*)&ram_data.cmd_obc_rwa1,
		(uint8_t*)&ram_data.sen_obc_rwa1,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_rwa1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,35.264,-45.0}}
	);
	mydevice[(int)device_no_t::obc_rwa2].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_rwa,
		(uint8_t*)&ram_data.cmd_obc_rwa2,
		(uint8_t*)&ram_data.sen_obc_rwa2,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_rwa2}
		,angle_array_t<1>{{sat_dir_enum_t::yPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{-35.264,0.0,-45.0}}
	);
	mydevice[(int)device_no_t::obc_rwa3].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_rwa,
		(uint8_t*)&ram_data.cmd_obc_rwa3,
		(uint8_t*)&ram_data.sen_obc_rwa3,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_rwa3}
		,angle_array_t<1>{{sat_dir_enum_t::xMINUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,-35.264,-45.0}}
	);
	mydevice[(int)device_no_t::obc_rwa4].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_rwa,
		(uint8_t*)&ram_data.cmd_obc_rwa4,
		(uint8_t*)&ram_data.sen_obc_rwa4,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_rwa4}
		,angle_array_t<1>{{sat_dir_enum_t::yMINUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{35.264,0.0,-45.0}}
	);
	mydevice[(int)device_no_t::cube_acs].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_acs,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::cube_ads].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_ads,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::cube_sun].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_sun[0],
		0.0001,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_cube_sun}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{180.0,0.0,90.0}}
	);
	mydevice[(int)device_no_t::cube_mag].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_mag[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_cube_mag}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{180.0,0.0,90.0}}
	);
	mydevice[(int)device_no_t::cube_gyro].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_gyro[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::cube_nadir].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::nadir,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_nadir[0],
		0.0001,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_cube_nadir}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,-90.0}}
	);
	mydevice[(int)device_no_t::cube_posvel_ecef].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::gps,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_posvel_ecef[0],
		0.25,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::cube_est_rate].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_est_rate[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::cube_est_quat].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::star,
		nullptr,
		(uint8_t*)&ram_data.sen_cube_est_quat[0],
		0.0001,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::cube_mtq1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::cube_mtq,
		(uint8_t*)&ram_data.cmd_cube_mtq1,
		(uint8_t*)&ram_data.sen_cube_mtq1,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_cube_mtq1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::cube_mtq2].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::cube_mtq,
		(uint8_t*)&ram_data.cmd_cube_mtq2,
		(uint8_t*)&ram_data.sen_cube_mtq2,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_cube_mtq2}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::cube_mtq3].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::cube_mtq,
		(uint8_t*)&ram_data.cmd_cube_mtq3,
		(uint8_t*)&ram_data.sen_cube_mtq3,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_cube_mtq3}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::cube_rwa1].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::cube_rwa,
		(uint8_t*)&ram_data.cmd_cube_rwa1,
		(uint8_t*)&ram_data.sen_cube_rwa1,
		1.0,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_cube_rwa1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::cube_rwa2].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::cube_rwa,
		(uint8_t*)&ram_data.cmd_cube_rwa2,
		(uint8_t*)&ram_data.sen_cube_rwa2,
		1.0,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_cube_rwa2}
		,angle_array_t<1>{{sat_dir_enum_t::yMINUS,sat_dir_enum_t::yMINUS,sat_dir_enum_t::yMINUS,sat_dir_enum_t::yMINUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::cube_rwa3].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::cube_rwa,
		(uint8_t*)&ram_data.cmd_cube_rwa3,
		(uint8_t*)&ram_data.sen_cube_rwa3,
		1.0,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_cube_rwa3}
		,angle_array_t<1>{{sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::mem].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_mem,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::rwa].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_rwa,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::mtq].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_mtq,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::can].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_can,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::uart].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_uart,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::i2c].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_i2c,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::slave].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_slave,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::acs].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_acs,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::ads].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_ads,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::run].init_info(device_info_t<DEV_TYPE_TSC1>{
		device_state_t::standby,
		DEV_TYPE_TSC1::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_run,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
}

#endif // KM_DEVICE_HH
