#ifndef INC_DEV_TYPE_ABOARD_H_
#define INC_DEV_TYPE_ABOARD_H_
#include "main.h"
#include "MEMORY_ABOARD.h"
#include "REG_MAP/newdevice.h"
#include <stdint.h>
typedef enum
{
    nothing,
    unix_time,
    obc_imu1,
    obc_imu2,
    obc_mag1,
    obc_mag2,
    obc_temp1,
    obc_current,
    model_igrf,
    model_sun,
    model_posvel_ecef,
    sat_inertia,
    mtq1,
    mtq2,
    mtq3,
    rwa1,
    rwa2,
    rwa3,
    rwa4,
    sun1,
    sun2,
    sun3,
    sun4,
    mag1,
    mag2,
    gyro1,
    gps_data,
    star_pu,
    acs,
    ads,
    run,
    uart,
} device_no_t;

enum class DEV_TYPE_ABOARD: uint8_t
{
	nothing = 0,
	clock = 1,
	gyro = 2,
	magnet = 3,
	temp = 4,
	current = 5,
	sunsen = 6,
	gps = 7,
	inertia = 8,
	mtq = 9,
	rwa = 10,
	star = 11,
	obc_mode = 12,
};
// Declare class array to store device states
#define DEVICE_NMAX_DEV_TYPE_ABOARD 33
NEW_DEVICE_STATE<DEV_TYPE_ABOARD> mydevice[DEVICE_NMAX_DEV_TYPE_ABOARD];

// Function to initialize device parameters
void init_device()
{
    // Initialize devices with corresponding command and sense pointers
	mydevice[(int)device_no_t::nothing].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::nothing,
		nullptr,
		(uint8_t*)&ram_data.sen_nothing,
		0.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::unix_time].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::clock,
		nullptr,
		(uint8_t*)&rom_data.sen_unix_time,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_imu1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_imu1[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_imu1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,90.0,180.0}}
	);
	mydevice[(int)device_no_t::obc_imu2].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_imu2[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_obc_imu2}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{90.0,0.0,90.0}}
	);
	mydevice[(int)device_no_t::obc_mag1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_mag1[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_mag2].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_mag2[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_temp1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::temp,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_temp1,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::obc_current].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::current,
		nullptr,
		(uint8_t*)&ram_data.sen_obc_current,
		0.01,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::model_igrf].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_model_igrf[0],
		1.0,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::model_sun].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_model_sun[0],
		1.0,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::model_posvel_ecef].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::gps,
		nullptr,
		(uint8_t*)&ram_data.sen_model_posvel_ecef[0],
		1.0,
		0,
		6,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::sat_inertia].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::inertia,
		nullptr,
		(uint8_t*)&rom_data.sen_sat_inertia[0],
		1.0,
		0,
		6,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::mtq1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::mtq,
		(uint8_t*)&ram_data.cmd_mtq1,
		(uint8_t*)&ram_data.sen_mtq1,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_mtq1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::mtq2].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::mtq,
		(uint8_t*)&ram_data.cmd_mtq2,
		(uint8_t*)&ram_data.sen_mtq2,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_mtq2}
		,angle_array_t<1>{{sat_dir_enum_t::yPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::yPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::mtq3].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::mtq,
		(uint8_t*)&ram_data.cmd_mtq3,
		(uint8_t*)&ram_data.sen_mtq3,
		0.001,
		1,
		1,
		device_axis_t::single,
		&rom_data.angle_mtq3}
		,angle_array_t<1>{{sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::rwa1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::rwa,
		(uint8_t*)&ram_data.cmd_rwa1,
		(uint8_t*)&ram_data.sen_rwa1,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_rwa1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,35.264,-45.0}}
	);
	mydevice[(int)device_no_t::rwa2].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::rwa,
		(uint8_t*)&ram_data.cmd_rwa2,
		(uint8_t*)&ram_data.sen_rwa2,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_rwa2}
		,angle_array_t<1>{{sat_dir_enum_t::yPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{-35.264,0.0,-45.0}}
	);
	mydevice[(int)device_no_t::rwa3].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::rwa,
		(uint8_t*)&ram_data.cmd_rwa3,
		(uint8_t*)&ram_data.sen_rwa3,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_rwa3}
		,angle_array_t<1>{{sat_dir_enum_t::xMINUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,-35.264,-45.0}}
	);
	mydevice[(int)device_no_t::rwa4].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::rwa,
		(uint8_t*)&ram_data.cmd_rwa4,
		(uint8_t*)&ram_data.sen_rwa4,
		1.0,
		1,
		1,
		device_axis_t::multi_axis,
		&rom_data.angle_rwa4}
		,angle_array_t<1>{{sat_dir_enum_t::yMINUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{35.264,0.0,-45.0}}
	);
	mydevice[(int)device_no_t::sun1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_sun1[0],
		0.0001,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_sun1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::sun2].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_sun2[0],
		0.0001,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_sun2}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::sun3].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_sun3[0],
		0.0001,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_sun3}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::sun4].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::sunsen,
		nullptr,
		(uint8_t*)&ram_data.sen_sun4[0],
		0.0001,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_sun4}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{0.0,0.0,0.0}}
	);
	mydevice[(int)device_no_t::mag1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_mag1[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_mag1}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{180.0,0.0,90.0}}
	);
	mydevice[(int)device_no_t::mag2].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::magnet,
		nullptr,
		(uint8_t*)&ram_data.sen_mag2[0],
		0.01,
		0,
		3,
		device_axis_t::multi_axis,
		&rom_data.angle_mag2}
		,angle_array_t<1>{{sat_dir_enum_t::xPLUS,sat_dir_enum_t::xPLUS,sat_dir_enum_t::yPLUS,sat_dir_enum_t::zPLUS},
		{180.0,0.0,90.0}}
	);
	mydevice[(int)device_no_t::gyro1].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::gyro,
		nullptr,
		(uint8_t*)&ram_data.sen_gyro1[0],
		0.01,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::gps_data].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::gps,
		nullptr,
		(uint8_t*)&ram_data.sen_gps_data[0],
		0.25,
		0,
		6,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::star_pu].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::star,
		nullptr,
		(uint8_t*)&ram_data.sen_star_pu[0],
		0.0001,
		0,
		3,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::acs].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_acs,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::ads].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_ads,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::run].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_run,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
	mydevice[(int)device_no_t::uart].init_info(device_info_t<DEV_TYPE_ABOARD>{
		device_state_t::standby,
		DEV_TYPE_ABOARD::obc_mode,
		nullptr,
		(uint8_t*)&ram_data.sen_uart,
		1.0,
		0,
		1,
		device_axis_t::nothing,
		nullptr}
	);
}

#endif // KM_DEVICE_HH
