/**
 ******************************************************************************
 * @file    csp_library_config.h
 * @brief   CSP Library Configuration (Auto-generated by WAF build system)
 * @details This file contains all libcsp library configuration parameters.
 *          DO NOT EDIT THIS FILE MANUALLY - it is auto-generated by the
 *          WAF build system. All manual changes will be lost.
 *
 *          For application-specific CSP configurations, use csp_app_params.h
 *          For module enable/disable, use app_modules_config.h
 ******************************************************************************
 */

#ifndef CSP_LIBRARY_CONFIG_H
#define CSP_LIBRARY_CONFIG_H

/* ======================================================================== */
/*                        VERSION AND PLATFORM INFO                        */
/* ======================================================================== */

#define GIT_REV "unknown"
#define LIBCSP_VERSION "1.6"

/* Platform Selection */
#define CSP_FREERTOS             1
/* #undef CSP_POSIX */
/* #define CSP_WINDOWS 1 */
/* #undef CSP_MACOSX */

/* Endian Configuration */
#define CSP_LITTLE_ENDIAN        1
/* #undef CSP_BIG_ENDIAN */

//#define CSP_RTABLE_STATIC
#define CSP_RTABLE_CIDR

/* ======================================================================== */
/*                        DEBUG AND LOGGING CONFIGURATION                  */
/* ======================================================================== */

#define CSP_DEBUG                1
#define CSP_DEBUG_TIMESTAMP      1
#define CSP_USE_EXTERNAL_DEBUG   0

#define CSP_LOG_LEVEL_DEBUG      1
#define CSP_LOG_LEVEL_INFO       1
#define CSP_LOG_LEVEL_WARN       1
#define CSP_LOG_LEVEL_ERROR      1

/* ======================================================================== */
/*                        CSP PROTOCOL FEATURES                             */
/* ======================================================================== */

#define CSP_USE_RDP              1
#define CSP_USE_RDP_FAST_CLOSE   0
#define CSP_USE_CRC32            1
#define CSP_USE_HMAC             1
#define CSP_USE_XTEA             1
#define CSP_USE_PROMISC          1
#define CSP_USE_QOS              0
#define CSP_USE_DEDUP            1

/* ======================================================================== */
/*                        CSP DEFAULT SERVER                                */
/* ======================================================================== */

#define CSP_DEFAULT_PORT                 10   /**< CSP port for default server */
#define CSP_DEFAULT_SERVER_NAME "CSPDefServ"
#define CSP_DEFAULT_SERVER_PRIORITY      osPriorityNormal
#define CSP_DEFAULT_SERVER_STACK         (1024 * 2)
#define CSP_DEFAULT_SERVER_AUTO_START 1

/* ======================================================================== */
/*                        CSP ROUTE MANAGER                                */
/* ======================================================================== */

#define CSP_ROUTE_MANAGER_PORT   9
#define CSP_ROUTE_MANAGER_RPS_MTU 254

/* ======================================================================== */
/*                        CSP TIME PROTOCOL (CTP)                          */
/* ======================================================================== */

#define CSP_CTP_PORT                     22   /**< CSP port for time manager */
#define CSP_CTP_CON_MAX                  5    /**< Number of CSP connections for time manager */
#define CSP_CTP_SERVER_BROADCAST_PERIOD  0    /**< Time server broadcast period (0 = disable) */

#define CSP_CTP_CLIENT_SERVER_ADDR       9    /**< Time server address for auto sync */
#define CSP_CTP_CLIENT_UPDATE_PERIOD     60000 /**< Time client auto update period (ms) */

#define CSP_CTP_SERVER_THREAD_NAME       "TimeDefServ"
#define CSP_CTP_SERVER_THREAD_PRIORITY   osPriorityNormal
#define CSP_CTP_SERVER_THREAD_STACK 1024
#define CSP_CTP_SERVER_THREAD_AUTO_START 1

#define CSP_CTP_CLIENT_THREAD_NAME       "TimeDefCli"
#define CSP_CTP_CLIENT_THREAD_PRIORITY   osPriorityNormal
#define CSP_CTP_CLIENT_THREAD_STACK 1024
#define CSP_CTP_CLIENT_THREAD_AUTO_START 0

/* ======================================================================== */
/*                        CSP THREAD MANAGER                               */
/* ======================================================================== */

#define CSP_THREAD_MANAGER_PORT          20   /**< CSP port for thread manager */
#define CSP_THREAD_MANAGER_CON_MAX       5    /**< Number of CSP connections for thread manager */
#define CSP_THREAD_MANAGER_MAX_NUM       12   /**< Maximum threads thread manager can handle */
#define CSP_THREAD_MANAGER_NAME_LENGTH   16   /**< Maximum thread name length */
#define CSP_THREAD_MANAGER_RPS_MTU       196  /**< Maximum length of CSP response message */

#define CSP_THREAD_SERVER_NAME           "ThreadDefServ"
#define CSP_THREAD_SERVER_PRIORITY       osPriorityNormal
#define CSP_THREAD_SERVER_STACK  1024
#define CSP_THREAD_SERVER_AUTO_START 1

/* ======================================================================== */
/*                        CSP CONFIG MANAGER                               */
/* ======================================================================== */

#define CSP_CCP_PORT                     19   /**< CSP port for config manager */
#define CSP_CONFIG_MANAGER_CON_MAX       5    /**< Number of CSP connections for config manager */
#define CSP_CONFIG_MANAGER_RPS_MTU       224  /**< Maximum length of CSP response message */

#define CSP_CONFIG_SERVER_NAME "ConfigDefServ"
#define CSP_CONFIG_SERVER_PRIORITY       osPriorityNormal
#define CSP_CONFIG_SERVER_STACK          (1024 * 4)
#define CSP_CONFIG_SERVER_AUTO_START 1

/* ======================================================================== */
/*                        CSP LOG MANAGER                                  */
/* ======================================================================== */

#define CSP_LOG_MANAGER_PORT             18   /**< CSP port for log manager */
#define CSP_LOG_MANAGER_CON_MAX          5    /**< Number of CSP connections for log manager */
#define CSP_LOG_MANAGER_RPS_MTU          224  /**< Maximum length of CSP response message */

#define CSP_LOG_SERVER_NAME "LogDefServ"
#define CSP_LOG_SERVER_PRIORITY          osPriorityNormal
#define CSP_LOG_SERVER_STACK     1024
#define CSP_LOG_SERVER_AUTO_START 1

/* ======================================================================== */
/*                        CSP FILE MANAGER                                 */
/* ======================================================================== */

#define CSP_FILE_MANAGER_PORT            17   /**< CSP port for file manager */
#define CSP_FILE_MANAGER_CON_MAX         10   /**< Number of CSP connections for file manager */
#define CSP_FILE_MANAGER_RPS_MTU         238  /**< Maximum length of CSP response message */
#define CSP_FILE_MANAGER_PATH_MAX        192  /**< Maximum length of file path */

#define CSP_FILE_SERVER_NAME "FileDefServ"
#define CSP_FILE_SERVER_PRIORITY         osPriorityNormal
#define CSP_FILE_SERVER_STACK            (1024 * 5)
#define CSP_FILE_SERVER_AUTO_START 1

#define CSP_FILE_MAX_RETRIES     5
#define CSP_FILE_TIMEOUT_MS      2000
#define CSP_FILE_ACK_TIMEOUT_MS  1000
#define CSP_FILE_MAX_CHUNK               (CSP_FILE_MANAGER_RPS_MTU - 10)
#define CSP_FILE_UPLOAD_TMP_SUFFIX       ".upload.tmp"
#define CSP_FILE_DOWNLOAD_TMP_SUFFIX     ".download.tmp"

/* ======================================================================== */
/*                        CSP DATA MONITOR                                 */
/* ======================================================================== */

#define CSP_DATA_MONITOR_PORT            16   /**< CSP port for data monitor */
#define CSP_DATA_MONITOR_CON_MAX         5    /**< Number of CSP connections for data monitor */
#define CSP_DATA_MONITOR_MAX_TASK        5    /**< Maximum threads data monitor can handle */
#define CSP_DATA_MONITOR_NAME_LENGTH     16   /**< Maximum name length for data monitor */
#define CSP_DATA_MONITOR_RPS_MTU         224  /**< Maximum length of CSP response message */

#define CSP_DATA_MONITOR_SERVER_NAME "DataMonDefServ"
#define CSP_DATA_MONITOR_SERVER_PRIORITY osPriorityNormal
#define CSP_DATA_MONITOR_SERVER_STACK 2048
#define CSP_DATA_MONITOR_SERVER_AUTO_START 1

/* ======================================================================== */
/*                        CSP REGISTER SERVICE                              */
/* ======================================================================== */

#define REGISTER_PORT_DEFAULT    24
#define REG_SVC_SERVER_NAME "RegSvcDef"
#define REG_SVC_SERVER_PRIORITY          osPriorityHigh
#define REG_SVC_SERVER_STACK     1024
#define REG_SVC_SERVER_AUTO_START 1
#define REG_SVC_CON_BACKLOG      10
#define REG_SVC_ACCEPT_TIMEOUT_MS 1000
#define REG_SVC_READ_TIMEOUT_MS  10

/* ======================================================================== */
/*                        KISS INTERFACE CONFIGURATION                     */
/* ======================================================================== */

#define CONFIG_CSP_UART_DEVICE_NUM 1
#define CONFIG_CSP_UART_RX_BUFFER_LENGTH 512
#define CONFIG_CSP_UART_TX_BUFFER_LENGTH 256
#define CONFIG_CSP_CAN_DEVICE_NUM 1

#endif /* CSP_LIBRARY_CONFIG_H */
